spring:
    datasource:
        url: jdbc:mysql://localhost:3306/salesandinventorydb?createDatabaseIfNotExist=true
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
